# Generated by Django 4.2.9 on 2024-01-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('SP', 'Spot'), ('SE', 'Session'), ('PR', 'Progress')], default='PR', max_length=20),
        ),
    ]
